import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useContext, useEffect } from "react";
import { CardFormContainer } from "../components/CardFormContainer/CardFormContainer";
import { HomeHeader } from "../components/HomeHeader/HomeHeader";
import { NiceCardContainer } from "../components/NiceCardContainer/NiceCardContainer";
import { NiceClassContext } from "../context/NiceClassProvider";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    const { niceClass } = useContext(NiceClassContext);

    useEffect(() => {}, [niceClass]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {niceClass ? (
                    <HomeHeader type={"secondary"} />
                ) : (
                    <HomeHeader type={"main"} />
                )}

                {niceClass ? (
                    niceClass.niceClass.length <= 3 ? (
                        <NiceCardContainer />
                    ) : (
                        ""
                    )
                ) : (
                    <CardFormContainer />
                )}
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
